name: Daily MF Report

on:
  schedule:
    - cron: "0 6 ** 1-5" # 11:30AM IST (6:00 AM UTC) every weekday
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version:"20"
          cache:"npm"
      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run daily pipeline
        run: npx tsx src/main.ts
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
          RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
          FROM_MAIL: ${{secrets.FROM_MAIL}}
          TO_MAIL: ${{secrets.TO_MAIL}}
